class Setting:
    MIN_WINDOW_WIDTH = 720
    MIN_WINDOW_HEIGHT = 720

    WINDOW_WIDTH = 1280
    WINDOW_HEIGHT = 720

    MENU_WIDTH = WINDOW_WIDTH
    MENU_HEIGHT = 50

    APPLICATION_WIDTH = WINDOW_WIDTH
    APPLICATION_HEIGHT = WINDOW_HEIGHT - MENU_HEIGHT

    APPLICATION_PARAMETER_SIDEBAR_WIDTH = 200
    APPLICATION_PARAMETER_SIDEBAR_HEIGHT = APPLICATION_HEIGHT

    APPLICATION_IMAGE_PREVIEW_WIDTH = APPLICATION_WIDTH - APPLICATION_PARAMETER_SIDEBAR_WIDTH
    APPLICATION_IMAGE_PREVIEW_HEIGHT = APPLICATION_HEIGHT

    OPTION_IMAGE_SHARPENING = "Image Sharpening"
    OPTION_PANORAMA = "Panorama"
    OPTION_HDR_IMAGE = "HDR Image"
    OPTION_SRCNN = "SRCNN"

    COLOR_BLACK = "#000"
    COLOR_GRAY = "#555"
    COLOR_WHITE = "#FFF"

    COLOR_BACKGROUND = COLOR_BLACK
    COLOR_TEXT = COLOR_WHITE

