class Setting:
    MIN_WINDOW_WIDTH = 720
    MIN_WINDOW_HEIGHT = 720

    WINDOW_WIDTH = 1280
    WINDOW_HEIGHT = 720

    MENU_WIDTH = WINDOW_WIDTH
    MENU_HEIGHT = 50

    OPTION_IMAGE_SHARPENING = "Image Sharpening"
    OPTION_PANORAMA = "Panorama"
    OPTION_HDR_IMAGE = "HDR Image"
    OPTION_SRCNN = "SRCNN"

